spark {
  app {
    name = "singularity-spark-app"
    master = "local[*]"
  }
  
  sql {
    adaptive {
      enabled = true
      coalescePartitions {
        enabled = true
      }
    }
  }
  
  streaming {
    checkpoint-base-path = "/tmp/spark-checkpoints"
  }
  
  cluster-info {
    enable-lineage-tracking = false
  }
}
